[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/admin-secret-panel"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200